pom.xml

Setup for deployment to Maven Central

---

logging/src/main/java/se/fortnox/reactivewizard/logging/LoggingFactory.java

Needed becuase we have configuration in different modules.
Also changed so that you can configure appenders fully from yml without specifying anything in the log4j.properties.

Load log4j.properties from multiple locations

---

utils/src/main/java/se/fortnox/reactivewizard/util/AccessorUtil.java
utils/src/main/java/se/fortnox/reactivewizard/util/FieldGetter.java
utils/src/main/java/se/fortnox/reactivewizard/util/FieldSetter.java
utils/src/main/java/se/fortnox/reactivewizard/util/MethodGetter.java
utils/src/main/java/se/fortnox/reactivewizard/util/MethodSetter.java
utils/src/main/java/se/fortnox/reactivewizard/util/ReflectionUtil.java
utils/src/test/java/se/fortnox/reactivewizard/util/AccessorTest.java
utils/src/test/java/se/fortnox/reactivewizard/util/FieldGetterTest.java
utils/src/test/java/se/fortnox/reactivewizard/util/FieldSetterTest.java
utils/src/test/java/se/fortnox/reactivewizard/util/MethodGetterTest.java
utils/src/test/java/se/fortnox/reactivewizard/util/MethodSetterTest.java

With my changes to better support inheritance with our reflection stuff I failed to take into account that you can, in fact, use classes without generics... This PR fixes that.

Fix issues with subclassing non-generic classes.

---

utils/src/main/java/se/fortnox/reactivewizard/util/AccessorUtil.java

This I should have seen coming...

Tweak AccessorUtil.typesByGenericName to work with any hierarchy

---

bootstrap/src/main/java/se/fortnox/reactivewizard/Main.java
config/src/main/java/se/fortnox/reactivewizard/config/ConfigAutoBindModule.java
config/src/main/java/se/fortnox/reactivewizard/config/ConfigFactory.java
config/src/test/java/se/fortnox/reactivewizard/config/ConfigFactoryTest.java
config/src/test/java/se/fortnox/reactivewizard/config/TestInjector.java

Injection of ConfigFactory instead of explicit creation

Injection of ConfigFactory

---

config/src/test/java/se/fortnox/reactivewizard/config/TestInjector.java
config/src/test/java/se/fortnox/reactivewizard/config/TestTestInjector.java

Missed to allow the TestInjector to accept a config file as argument to fit my purpose

Enable config file passed in to TestInjector

---

config/src/main/java/se/fortnox/reactivewizard/config/ConfigAutoBindModule.java
config/src/main/java/se/fortnox/reactivewizard/config/ConfigReader.java
config/src/test/java/se/fortnox/reactivewizard/config/ConfigReaderTest.java
config/src/test/java/se/fortnox/reactivewizard/config/EmptyConfig.java
config/src/test/java/se/fortnox/reactivewizard/config/TestInjector.java
config/src/test/resources/testconfig.yml
jaxrs/src/main/java/se/fortnox/reactivewizard/jaxrs/JaxRsMeta.java
jaxrs/src/test/java/se/fortnox/reactivewizard/jaxrs/JaxRsMetaTest.java
pom.xml
server/src/main/java/se/fortnox/reactivewizard/server/JaxRsResourceRegistry.java
server/src/main/java/se/fortnox/reactivewizard/server/ServerModule.java
validation/pom.xml
validation/src/main/java/se/fortnox/reactivewizard/validation/JaxRsParameterNameResolver.java
validation/src/main/java/se/fortnox/reactivewizard/validation/ValidatingConfigFactory.java
validation/src/main/java/se/fortnox/reactivewizard/validation/ValidatingProxy.java
validation/src/main/java/se/fortnox/reactivewizard/validation/ValidationFailedException.java
validation/src/main/java/se/fortnox/reactivewizard/validation/ValidationFieldError.java
validation/src/main/java/se/fortnox/reactivewizard/validation/ValidationModule.java
validation/src/main/java/se/fortnox/reactivewizard/validation/ValidatorUtil.java
validation/src/test/java/se/fortnox/reactivewizard/validation/ConfigValidationTest.java
validation/src/test/java/se/fortnox/reactivewizard/validation/ResourceValidationTest.java
validation/src/test/java/se/fortnox/reactivewizard/validation/ValidationExamples.java
validation/src/test/resources/correctconfig.yml
validation/src/test/resources/invalidconfig.yml

With support for validating config files and resource calls

Added validation module

---

validation/src/main/java/se/fortnox/reactivewizard/validation/ValidatingProxy.java
validation/src/main/java/se/fortnox/reactivewizard/validation/ValidatorUtil.java

* to be used in tests that want to verify the validation logic of the resources;
* minor imports clean up.

Make "ValidatingProxy" public

---

pom.xml

Internal framework wants rxjava 1.2.10 since commit e9bce4b6912

Align rxjava with internal framework

---

client/src/test/java/se/fortnox/reactivewizard/client/HttpClientTest.java

Should hopefully resolve #70 as well as increase coverage in HttpClient a tiny bit

Try to fix flaky tests

---

.editorconfig
binding/src/main/java/se/fortnox/reactivewizard/binding/AutoBindModules.java
checkstyle.xml

Add Editorconfig file to help developers use the correct indentations in the repo and checkstyles to validate that they stay correct.

Editorconfig & checkstyle for indents

---

server/pom.xml

We should probably make travis check this on pr builds but for now we lower the limit

lowering coverage limit to make the build work

---

client/src/main/java/se/fortnox/reactivewizard/client/HttpClient.java
client/src/test/java/se/fortnox/reactivewizard/client/HttpClientTest.java

Logging information when a response is empty

warn log if empty response

---

README.md
dbmigrate/pom.xml
dbmigrate/src/main/java/liquibase/ext/TimeoutLockService.java
dbmigrate/src/main/java/se/fortnox/reactivewizard/dbmigrate/LiquibaseAutoBindModule.java
dbmigrate/src/main/java/se/fortnox/reactivewizard/dbmigrate/LiquibaseConfig.java
dbmigrate/src/main/java/se/fortnox/reactivewizard/dbmigrate/LiquibaseMigrate.java
dbmigrate/src/test/java/se/fortnox/reactivewizard/dbmigrate/LiquibaseMigrateTest.java
dbmigrate/src/test/java/se/fortnox/reactivewizard/dbmigrate/TimeoutLockServiceTest.java
dbmigrate/src/test/resources/migrations.xml
pom.xml

Uses lquibase to migrate the database of your system.

dbmigrate module

---

README.md

Added reactivewizard-dbmigrate to the example in the readme, so that the migrations will be executed when following the guide.

Updated readme with db-migrate

---

.travis.yml

Don't mind this PR, need it for testing my changes :)

WIP Run SonarCloud

---

client/src/main/java/se/fortnox/reactivewizard/client/HttpClient.java

In order to know what error was returned from an API we should log every error on every retry.

Now logs the error on every retry in HttpClient

---

client/src/main/java/se/fortnox/reactivewizard/client/HttpClientProvider.java

We need to make the http client provider more extendable to easier be able to have custom httpClients

making the http client provider more extendable

---

jaxrs-api/src/main/java/se/fortnox/reactivewizard/jaxrs/WebException.java
validation/src/main/java/se/fortnox/reactivewizard/validation/ValidationFailedException.java
validation/src/test/java/se/fortnox/reactivewizard/validation/ValidationExamples.java

Changing ValidationExceptions and WebExceptions with only FieldErrors to logLevel INFO

Validation exceptions should not be loglevel WARN but INFO

---

binding/src/main/java/se/fortnox/reactivewizard/binding/AutoBindModules.java
binding/src/main/java/se/fortnox/reactivewizard/binding/ClassScannerImpl.java
binding/src/main/java/se/fortnox/reactivewizard/binding/scanners/ClassScanner.java

Changed so that one single class scanner is used for both steps of finding the classes needed.
Also made it possible to extend the AutoBindModules class in order to change whitelist or blacklist in scanning, or to override the whole ClassScanner creation, allowing for caching in tests.

Optimized class scanning

---

dbmigrate/pom.xml
pom.xml

Upping to 4.1.45.Final for netty

upping versions to avoid vulnerability in netty

---

client/src/main/java/se/fortnox/reactivewizard/client/HttpClient.java
client/src/test/java/se/fortnox/reactivewizard/client/HttpClientTest.java

Make http method check first in withRetry() to stop all retries for POSTS

Stop retries for POST calls

---

api/src/main/java/se/fortnox/reactivewizard/CollectionOptions.java

so that classes used with @BeanParam annotations in resources can extend CollectionOptions to avoid extra parameters in resources

Adding QueryParam annotations to the CollectionOptions class

---

server/src/main/java/se/fortnox/reactivewizard/server/NoContentFixConfigurator.java
server/src/main/java/se/fortnox/reactivewizard/server/RwServer.java
server/src/test/java/se/fortnox/reactivewizard/server/NoContentFixConfiguratorTest.java

Making sure the NoContentFix is only added once

Making sure the no content fix is not called twice if it already exists

---

server/src/main/java/se/fortnox/reactivewizard/server/RwServer.java

Removing the host config for the server to listen to ip-adresses as well.

Removing the host configuration of the main server 

---

client/src/main/java/se/fortnox/reactivewizard/client/Response.java
client/src/test/java/se/fortnox/reactivewizard/client/HttpClientTest.java

Added a way to fetch cookie values to the full response

adding a method to retrieve cookie values from the response

---

metrics/src/main/java/se/fortnox/reactivewizard/metrics/MetricsOperator.java

Removing unwanted calls to subscribers request method.
All tests still passes so I take that as a good sign and will not add new tests just for this

removing explicit calls to subscribers request method.

---

metrics/pom.xml
metrics/src/main/java/se/fortnox/reactivewizard/metrics/Metrics.java
metrics/src/test/java/se/fortnox/reactivewizard/metrics/MetricsTest.java

The code coverage was improved to make sure things didn't break along with some minor cleanup of the code.

Upgrade metrics-core dependency 

---

pom.xml
test/pom.xml
test/src/main/java/se/fortnox/reactivewizard/test/observable/ObservableAssert.java
test/src/main/java/se/fortnox/reactivewizard/test/observable/ObservableAssertions.java
test/src/main/java/se/fortnox/reactivewizard/test/observable/ObservableThrowableAssert.java
test/src/test/java/se/fortnox/reactivewizard/test/ObservableAssertTest.java
test/src/test/java/se/fortnox/reactivewizard/test/ObservableThrowableAssertTest.java

Added helper classes to make it more convenient to use AssertJ(https://assertj.github.io/doc/) with observables.
Upped some tools dependencies.

Added ObservableAssertions

---

.github/workflows/on_release_publish_to_maven.yml

It seems the user-name should be in clear text and not encrypted
Also the setupjava seems to support gpg settings so trying that
https://github.com/actions/setup-java

trying another approach for nexus

---

test/src/main/java/se/fortnox/reactivewizard/test/WaitingTestUtils.java
test/src/test/java/se/fortnox/reactivewizard/test/WaitingTestUtilsTest.java

As a response to the problem:
As a developer I want to write a unit test that asserts that a condition is met in a certain time.

Adding WaitingTestUtils to the framework as a way to handle timing is an issue

---

client/src/test/java/se/fortnox/reactivewizard/client/HttpClientTest.java
client/src/test/java/se/fortnox/reactivewizard/client/RestClientFactoryTest.java
config/src/test/java/se/fortnox/reactivewizard/config/MockConfigFactory.java
dao/pom.xml
dao/src/test/java/se/fortnox/reactivewizard/db/CollectionOptionsTest.java
dao/src/test/java/se/fortnox/reactivewizard/db/DaoTransactionsTest.java
dao/src/test/java/se/fortnox/reactivewizard/db/MockDb.java
dao/src/test/java/se/fortnox/reactivewizard/db/ObservableStatementFactoryTest.java
dao/src/test/java/se/fortnox/reactivewizard/db/ParameterizedQueryTest.java
dao/src/test/java/se/fortnox/reactivewizard/db/deserializing/DeserializerUtilTest.java
dbmigrate/src/test/java/se/fortnox/reactivewizard/dbmigrate/LiquibaseAutoBindModuleTest.java
dbmigrate/src/test/java/se/fortnox/reactivewizard/dbmigrate/TimeoutLockServiceTest.java
pom.xml
server/src/test/java/se/fortnox/reactivewizard/server/CompositeRequestHandlerTest.java
server/src/test/java/se/fortnox/reactivewizard/server/ConnectionCounterTest.java
server/src/test/java/se/fortnox/reactivewizard/server/RwServerTest.java
test/src/main/java/se/fortnox/reactivewizard/test/LoggingMockUtil.java
test/src/main/java/se/fortnox/reactivewizard/test/TestUtil.java
test/src/test/java/se/fortnox/reactivewizard/test/TestUtilTest.java
utils/src/test/java/se/fortnox/reactivewizard/util/DebugUtilTest.java
utils/src/test/java/se/fortnox/reactivewizard/util/rx/FirstThenTest.java
utils/src/test/java/se/fortnox/reactivewizard/util/rx/IfThenElseTest.java
utils/src/test/java/se/fortnox/reactivewizard/util/rx/RxUtilsTest.java
validation/src/test/java/se/fortnox/reactivewizard/validation/ValidationExamples.java

Upgrading the ancient Mockito 1, partly in preparation for Java 17.

Upgrade to Mockito 3

---

jaxrs-api/src/main/java/se/fortnox/reactivewizard/jaxrs/SuppressPathCollision.java
jaxrs/src/main/java/se/fortnox/reactivewizard/jaxrs/CheckForCollidingPaths.java
jaxrs/src/main/java/se/fortnox/reactivewizard/jaxrs/CheckForMissingPathParams.java
jaxrs/src/main/java/se/fortnox/reactivewizard/jaxrs/JaxRsResources.java
jaxrs/src/main/java/se/fortnox/reactivewizard/jaxrs/SuppressPathCollision.java
jaxrs/src/test/java/se/fortnox/reactivewizard/jaxrs/CollidingTestInterfaces.java
jaxrs/src/test/java/se/fortnox/reactivewizard/jaxrs/JaxRsResourceTest.java

Added check for colliding resource paths on startup.
Added check for missing PathParam annotations on startup.
Closing PR #235 in favor of this.

Checking resources for colliding paths and missing path params on startup.

---

.github/workflows/on_release_publish_to_maven.yml

testing to add jdkFile in another place as well

missing jdkFile

---

api/README.md
binding/README.md
bootstrap/README.md
client/README.md
client/src/main/java/se/fortnox/reactivewizard/client/ReactorRxClientProvider.java
config/README.md
dao/README.md
dbmigrate/README.md
jaxrs-api-test/README.md
jaxrs-api/README.md
jaxrs-context/README.md
jaxrs/README.md
jaxrs/src/main/java/se/fortnox/reactivewizard/jaxrs/JaxRsRequestHandler.java
json/README.md
logging/README.md
metrics/README.md
server/README.md
test/README.md
utils/README.md
validation/README.md

README files for all the modules

---

binding/pom.xml
pom.xml

Updated reactor-bom and some other dependencies as well.

Updated classgraph dependency for better Java 17 support

---

dao/src/main/java/se/fortnox/reactivewizard/db/ObservableStatementFactory.java
dao/src/main/java/se/fortnox/reactivewizard/db/transactions/ConnectionScheduler.java
dao/src/main/java/se/fortnox/reactivewizard/db/transactions/DaoObservable.java
dao/src/main/java/se/fortnox/reactivewizard/db/transactions/DaoTransactionsImpl.java
dao/src/main/java/se/fortnox/reactivewizard/db/transactions/StatementConnectionScheduler.java
dao/src/main/java/se/fortnox/reactivewizard/db/transactions/StatementContext.java
dao/src/main/java/se/fortnox/reactivewizard/db/transactions/Transaction.java
dao/src/test/java/se/fortnox/reactivewizard/db/DaoTransactionsTest.java

Using connection provider and scheduler that was specified in the DbProxy that created the DaoObservables

Connection provider and scheduler

---

dao/src/main/java/se/fortnox/reactivewizard/db/transactions/DaoTransactionsFluxImpl.java
dao/src/main/java/se/fortnox/reactivewizard/db/transactions/DaoTransactionsImpl.java
dao/src/main/java/se/fortnox/reactivewizard/db/transactions/TransactionExecutor.java
dao/src/test/java/se/fortnox/reactivewizard/db/DaoTransactionsTest.java

Minor change getting away from the constructor parameter in DaoTransactionFluxImpl

Wanted to get away from the constructor parameter in

---

jaxrs/src/test/java/se/fortnox/reactivewizard/mocks/MockHttpServerRequest.java
jaxrs/src/test/java/se/fortnox/reactivewizard/mocks/MockHttpServerResponse.java
pom.xml
server/src/main/java/se/fortnox/reactivewizard/server/RwServer.java
server/src/test/java/se/fortnox/reactivewizard/server/RwServerTest.java

latest reactor bom and netty version

---

pom.xml

* slf4j-api
* snakeyaml
* classgraph
* nexus-staging-maven-plugin
* maven-compiler-plugin
* maven-javadoc-plugin

Upping version for:

---

client/src/test/java/se/fortnox/reactivewizard/client/RequestParameterSerializersTest.java
client/src/test/java/se/fortnox/reactivewizard/client/RestClientFactoryTest.java
dao/src/test/java/se/fortnox/reactivewizard/db/DaoTransactionsTest.java
jaxrs-api-test/pom.xml
jaxrs-api-test/src/test/java/se/fortnox/reactivewizard/jaxrs/WebExceptionMatcherTest.java
jaxrs-context/src/test/java/se/fortnox/reactivewizard/jaxrs/context/JaxRsRequestContextInterceptorTest.java
jaxrs-context/src/test/java/se/fortnox/reactivewizard/jaxrs/context/JaxRsRequestContextModuleTest.java
jaxrs-context/src/test/java/se/fortnox/reactivewizard/jaxrs/context/JaxRsRequestContextPropagationTest.java
jaxrs-context/src/test/java/se/fortnox/reactivewizard/jaxrs/context/JaxRsRequestContextTest.java
jaxrs/src/test/java/se/fortnox/reactivewizard/jaxrs/JaxRsModuleTest.java
jaxrs/src/test/java/se/fortnox/reactivewizard/jaxrs/JaxRsRequestHandlerTest.java
jaxrs/src/test/java/se/fortnox/reactivewizard/jaxrs/JaxRsResourceCallContextTest.java
pom.xml
test/pom.xml
test/src/main/java/se/fortnox/reactivewizard/test/TestUtil.java
test/src/test/java/se/fortnox/reactivewizard/test/TestUtilTest.java
test/src/test/java/se/fortnox/reactivewizard/test/WaitingTestUtilsTest.java
utils/src/test/java/se/fortnox/reactivewizard/util/ReactiveDecoratorTest.java
validation/src/test/java/se/fortnox/reactivewizard/validation/ValidationExamples.java

Removed fest lib since it is no longer maintained, and replaced with assertj.

Removed fest lib

---

api/src/main/java/se/fortnox/reactivewizard/CollectionOptions.java
client/src/test/java/se/fortnox/reactivewizard/client/HttpClientTest.java
dao/src/main/java/se/fortnox/reactivewizard/db/paging/PagingOperator.java
dao/src/test/java/se/fortnox/reactivewizard/db/MockDb.java
dao/src/test/java/se/fortnox/reactivewizard/db/paging/PagingOperatorTest.java
jaxrs/pom.xml
jaxrs/src/main/java/se/fortnox/reactivewizard/jaxrs/params/annotated/QueryParamResolver.java
jaxrs/src/test/java/se/fortnox/reactivewizard/jaxrs/StreamingDataTest.java
jaxrs/src/test/java/se/fortnox/reactivewizard/utils/JaxRsTestUtil.java

we need the CollectionOptions isLastRecord to be default false.
To allow this we need to change the strategy of only setting it to false when we have more items to always set the correct value onComplete in PagingOperator

To allow streaming results with CollectionOptions

---

api/pom.xml
binding/pom.xml
bootstrap/pom.xml
client/pom.xml
client/src/main/java/se/fortnox/reactivewizard/client/HttpClientConfig.java
config/pom.xml
dao/pom.xml
dbmigrate/pom.xml
jaxrs-api-test/pom.xml
jaxrs-api/pom.xml
jaxrs/pom.xml
json/pom.xml
metrics/pom.xml
pom.xml
server/pom.xml
utils/pom.xml
validation/pom.xml
validation/src/main/java/se/fortnox/reactivewizard/validation/JaxRsParameterNameResolver.java
validation/src/main/java/se/fortnox/reactivewizard/validation/ValidationFailedException.java
validation/src/main/java/se/fortnox/reactivewizard/validation/ValidationFieldError.java
validation/src/main/java/se/fortnox/reactivewizard/validation/ValidationModule.java
validation/src/main/java/se/fortnox/reactivewizard/validation/ValidatorUtil.java
validation/src/test/java/se/fortnox/reactivewizard/validation/ConfigValidationTest.java
validation/src/test/java/se/fortnox/reactivewizard/validation/ResourceValidationTest.java
validation/src/test/java/se/fortnox/reactivewizard/validation/ValidationExamples.java

Created properties for all dependency versions.
Upped jackson-bom, jacoco, classgraph and liquibase-slf4j.
Use jakarta-el instead of javax-el.
Removed unnecessary versions for dependencies on internal modules.

Dependencies updates and cleanup

---

pom.xml

Added dependency on netty-bom to avoid RequireUpperBoundDeps enforcer errors.

Added dependency on netty-bom

---

client/src/test/java/se/fortnox/reactivewizard/client/HttpClientTestUtil.java

Check for unnecessary stubbing should not be needed when using this util

Changed to lenient stubbing in the test util

---

pom.xml

Configure maven-deploy-plugin not to deploy any module unless the entire build is successful.

Only deploy if entire build is successful

---

README.md

Updated the main readme to use Project Reactor instead of RxJava.
Fixed some typos and removed outdated sections.

Updated the main readme

---

README.md
pom.xml
test/pom.xml

Changed to more recent slf4j implementation artifact and bumped version.
Updated some old versions and artifacts in the readme.

Updated slf4j artifact

---

dao/src/main/java/se/fortnox/reactivewizard/db/transactions/TransactionExecutor.java
dao/src/test/java/se/fortnox/reactivewizard/db/DaoTransactionsTest.java
utils/src/main/java/se/fortnox/reactivewizard/util/FluxRxConverter.java
utils/src/test/java/se/fortnox/reactivewizard/util/FluxRxConverterTest.java

Added documentation and some tests to FluxRxConverter.
Corrected error message for when dao calls are not decorated.

Improved documentation and corrected error message

---

dao/src/main/java/se/fortnox/reactivewizard/db/transactions/DaoTransactions.java
dao/src/main/java/se/fortnox/reactivewizard/db/transactions/DaoTransactionsImpl.java

No need for the publishers to be of the same type.

Removed unnecessary type restriction in DaoTransactions

---

binding/pom.xml
bootstrap/pom.xml
client/pom.xml
client/src/test/java/se/fortnox/reactivewizard/client/ClientBlockHoundIntegration.java
config/pom.xml
dao/pom.xml
jaxrs-api/src/main/java/se/fortnox/reactivewizard/jaxrs/WebException.java
jaxrs/pom.xml
jaxrs/src/test/java/se/fortnox/reactivewizard/JaxRsBlockHoundIntegration.java
json/pom.xml
pom.xml
server/pom.xml
server/src/test/java/se/fortnox/reactivewizard/BlockHoundTest.java
test/pom.xml
test/src/main/java/se/fortnox/reactivewizard/test/RwBlockHoundIntegration.java
utils/pom.xml

Activated Blockhound to detect blocking calls during tests.
https://github.com/reactor/BlockHound

Activated Blockhound

---

.github/workflows/scorecard.yml

https://github.com/ossf/scorecard

Add OSSF scorecard

---

.github/workflows/deploy_tag.yml

Fix failing build because of wrong version.

Use java 21 for all builds

---

client/src/main/java/se/fortnox/reactivewizard/client/HttpClient.java
client/src/main/java/se/fortnox/reactivewizard/client/HttpClientConfig.java
client/src/main/java/se/fortnox/reactivewizard/client/ReactorRxClientProvider.java
client/src/test/java/se/fortnox/reactivewizard/client/HttpClientConfigTest.java
client/src/test/java/se/fortnox/reactivewizard/client/HttpClientTest.java
client/src/test/resources/httpconfig.yml

- timeoutMs
- followRedirect
- path of URL used as API root

Improved HttpClientConfig
