FortnoxAB/reactive-wizard

utils/src/main/java/se/fortnox/reactivewizard/util/AccessorUtil.java, utils/src/main/java/se/fortnox/reactivewizard/util/FieldGetter.java, utils/src/main/java/se/fortnox/reactivewizard/util/FieldSetter.java, utils/src/main/java/se/fortnox/reactivewizard/util/Getter.java, utils/src/main/java/se/fortnox/reactivewizard/util/MethodGetter.java, utils/src/main/java/se/fortnox/reactivewizard/util/MethodSetter.java, utils/src/main/java/se/fortnox/reactivewizard/util/ReflectionUtil.java, utils/src/test/java/se/fortnox/reactivewizard/util/FieldGetterTest.java, utils/src/test/java/se/fortnox/reactivewizard/util/FieldSetterTest.java, utils/src/test/java/se/fortnox/reactivewizard/util/MethodGetterTest.java, utils/src/test/java/se/fortnox/reactivewizard/util/MethodSetterTest.java, utils/src/test/java/se/fortnox/reactivewizard/util/ReflectionUtilTest.java
This change allows for better field- and method lookup when using class hierarchies.
The two issues this fixes are 
1) Allowing ReflectionUtil to create Getter and Setter instances for non-visible fields and methods in a superclass.
2) Allowing Getters and Setters to properly determine the return types and parameter types of fields and methods in a generic superclass.
=> ReflectionUtil - improve member lookup

client/src/test/java/se/fortnox/reactivewizard/client/HttpClientTest.java, dao/src/main/java/se/fortnox/reactivewizard/db/DbProxy.java, dao/src/main/java/se/fortnox/reactivewizard/db/ObservableStatementFactory.java
In order to use the same database for multiple connections without the overhead of creating the deserializers for each connection, a new method DbProxy.usingConnectionProvider was added to return a new DbProxy reusing everything but the connection provider.
=> Improvement in DbProxy allowing new connections providers

bootstrap/src/main/java/se/fortnox/reactivewizard/Main.java
Before this fix, the system might continue to run even though there was configuration errors, as the server thread is started during bind. An exception on Main thread would then just terminate the main thread while the server and therefore the system process would continue to run.
=> Shutdown on error

.codecov.yml
This causes more trouble than it gives value, so lets just disable this for now.
See #83 and #81 for examples.
=> Disable Codecov patch checks due to being unreliable

client/src/main/java/se/fortnox/reactivewizard/client/HttpClient.java, client/src/test/java/se/fortnox/reactivewizard/client/HttpClientTest.java
Description:
We've experienced weird HttpClient errors when using HttpClientProvider to access external third party api's, in all environments. It's hard to recreate error in tests, succeeded a couple of times then error magically disappeared. 
URISyntaxException are thrown in encode(...) when having colon (:) in query parameters since query parameters are parsed through java.net.URI. Colon are not permitted in paths. In most cases it works fine but in deployed environments it's not working for us.
Error:
java.net.URISyntaxException: Illegal character in scheme name at index ...
Fix:
Always use existing urlEncode(...) for all annotation of QueryParam instance.
=> urlEncode query parameters

client/src/main/java/se/fortnox/reactivewizard/client/HttpClient.java, client/src/test/java/se/fortnox/reactivewizard/client/HttpClientTest.java
It does not make any sense to retry these calls, as they would most likely give the same error again.
=> Do not retry http call when deserialization failed

dao/src/main/java/se/fortnox/reactivewizard/db/query/parts/ParamQueryPart.java, dao/src/test/java/se/fortnox/reactivewizard/db/query/parts/ParamQueryPartTest.java
This has been bothering me for some time. 
The error is now for example "Properties [bar, zap] cannot be found in class se.fortnox.reactivewizard.db.query.parts.ParamQueryPartTest$Foo" instead of "Properties [Ljava.lang.String;@6ad82709 cannot be found in []"
=> Improve ParamQueryPart.subPath error message

dao/src/main/java/se/fortnox/reactivewizard/db/DbProxyFactory.java
Changed to System.err.println since it will be more visible to the developer when running mvn commands.
=> Check dao classes to be compiled with -parameters flag

client/src/main/java/se/fortnox/reactivewizard/client/HttpClient.java, client/src/main/java/se/fortnox/reactivewizard/client/HttpClientConfig.java, client/src/main/java/se/fortnox/reactivewizard/client/RxClientProvider.java, client/src/test/java/se/fortnox/reactivewizard/client/HttpClientTest.java
1. Making the readTimeout on nettys HttpClient configurable instead of always 10 seconds
2. Making the HttpClient using the configured timeout as the default observable timeout.
=> PLAT-1578 - Make readTimeout configurable

client/src/main/java/se/fortnox/reactivewizard/client/HttpClient.java, client/src/main/java/se/fortnox/reactivewizard/client/RequestBuilder.java, client/src/main/java/se/fortnox/reactivewizard/client/RequestParameterSerializers.java, client/src/test/java/se/fortnox/reactivewizard/client/RequestParameterSerializersTest.java, config/src/main/java/se/fortnox/reactivewizard/config/ConfigReader.java, config/src/test/java/se/fortnox/reactivewizard/config/ConfigReaderTest.java, config/src/test/java/se/fortnox/reactivewizard/config/TestConfig.java, config/src/test/resources/testconfig.yml
Using Class.getDeclaredMethods() can return multiple methods for
addParameter (one taking the type argument as first argument and one
taking Object as the first argument) and since the order is unspecified
findFirst cannot be used.
Oh, the fix for reading all allowed environment variables in ConfigReader snuck in as well. I meant to separate that into another PR...
=> Bugfix: RequestParameterSerializers method filtering

config/src/main/java/se/fortnox/reactivewizard/config/ConfigReader.java, config/src/test/java/se/fortnox/reactivewizard/config/ConfigReaderTest.java
The replacement string (coming from an env var) needs to be treated as
a literal string. If it contains a regex (or any \ or $) and is not quoted it will be
treated as a regex when replacing the value.
=> Properly escape replacement string when replacing config variables

client/src/main/java/se/fortnox/reactivewizard/client/HttpClientConfig.java, client/src/main/java/se/fortnox/reactivewizard/client/RxClientProvider.java, client/src/test/java/se/fortnox/reactivewizard/client/HttpClientConfigTest.java, client/src/test/java/se/fortnox/reactivewizard/client/HttpClientTest.java
- Introduces an option "unsafeSecure" (default false) to make insecure requests.
- Allow the user to somewhat configure the SSL engine when there is
a need to do so (custom trustmanagers, not having a keystore on
file, etc).
=> Prefer a secure HTTP client when calling https services

client/src/main/java/se/fortnox/reactivewizard/client/RxClientProvider.java
Now a new SSL Engine will be created for each new connection. Otherwise the sslEnginge will be in a state where it thinks it has done a handshake when it in fact has not, since the connection is new.
=> Added factory method for SSL Engine.

dao/pom.xml, dao/src/main/java/se/fortnox/reactivewizard/db/ConnectionProviderImpl.java, dao/src/main/java/se/fortnox/reactivewizard/db/config/DatabaseConfig.java, dao/src/test/java/se/fortnox/reactivewizard/db/config/DatabaseConfigTest.java
These changes update the version of HikariCP and add a DatabaseConfig option to configure a socket timeout.
Is the default timeout of 5 minutes reasonable or should we perhaps use 10 minutes? 
If any query takes longer to execute than this timeout the connection will be closed.
=> Add database socket timeout

client/src/main/java/se/fortnox/reactivewizard/client/HttpClient.java, client/src/test/java/se/fortnox/reactivewizard/client/HttpClientTest.java
Workaround for occational emptys returned from the submit.
Will retry calls three times before actually returning empty.
=> retry the request if submit returns empty (rare occations)

jaxrs/pom.xml, pom.xml
CreationException has a method getMessage which nicely formats the cause of why an instance couldn't be created by the injector. Calling this method leads to an com.google.common.util.concurrent.UncheckedExecutionException:
> Caused by: java.lang.IllegalArgumentException: null
at com.google.inject.internal.asm.$ClassReader.<init>(Unknown Source)
at com.google.inject.internal.asm.$ClassReader.<init>(Unknown Source)
at com.google.inject.internal.asm.$ClassReader.<init>(Unknown Source)
at com.google.inject.internal.util.LineNumbers.<init>(LineNumbers.java:66)
at com.google.inject.internal.util.StackTraceElements$1.load(StackTraceElements.java:46)
at com.google.inject.internal.util.StackTraceElements$1.load(StackTraceElements.java:43)
at …
=> Log cause(s) of CreationException

dbmigrate/src/test/java/se/fortnox/reactivewizard/dbmigrate/LiquibaseAutoBindModuleTest.java, jaxrs/src/main/java/se/fortnox/reactivewizard/jaxrs/ByteBufCollector.java, jaxrs/src/main/java/se/fortnox/reactivewizard/jaxrs/JaxRsRequest.java, jaxrs/src/main/java/se/fortnox/reactivewizard/jaxrs/JaxRsRequestHandler.java, jaxrs/src/test/java/se/fortnox/reactivewizard/jaxrs/JaxRsRequestTest.java, jaxrs/src/test/java/se/fortnox/reactivewizard/jaxrs/JaxRsResourceTest.java, jaxrs/src/test/java/se/fortnox/reactivewizard/jaxrs/StatusTest.java, jaxrs/src/test/java/se/fortnox/reactivewizard/jaxrs/SynchronousResourcesTest.java, jaxrs/src/test/java/se/fortnox/reactivewizard/jaxrs/WrappedParamTest.java, jaxrs/src/test/java/se/fortnox/reactivewizard/utils/JaxRsTestUtil.java, server/src/main/java/se/fortnox/reactivewizard/server/ServerConfig.java, server/src/main/java/se/fortnox/reactivewizard/server/ServerModule.java, server/src/test/java/se/fortnox/reactivewizard/server/ServerConfigTest.java
It is currently possible to specify maxResponseSize in HttpClientConfig for responses. This PR lets you specify a maxRequestSize for _incoming_ requests.
=> Added maxRequestSize to ServerConfig to specify size of incoming req

jaxrs/src/main/java/se/fortnox/reactivewizard/jaxrs/JaxRsRequestHandler.java
Removed the varargs constructor to avoid accidentally hitting that constructor when adding new fields in the other constructors.
=> No var args constructor

dbmigrate/src/main/java/se/fortnox/reactivewizard/dbmigrate/LiquibaseAutoBindModule.java, dbmigrate/src/main/java/se/fortnox/reactivewizard/dbmigrate/LiquibaseMigrateProvider.java, dbmigrate/src/test/java/se/fortnox/reactivewizard/dbmigrate/LiquibaseAutoBindModuleTest.java, dbmigrate/src/test/java/se/fortnox/reactivewizard/dbmigrate/LiquibaseMigrateProviderTest.java
The eager creation of LiquibaseMigrate led to problems when creating injectors in tests where the dbmigration wasn't supposed to run.
Making it lazy fixed the problem
=> Making the liquibase migration lazy

config/src/test/java/se/fortnox/reactivewizard/config/TestInjector.java, config/src/test/java/se/fortnox/reactivewizard/config/TestTestInjector.java, dbmigrate/src/main/java/se/fortnox/reactivewizard/dbmigrate/LiquibaseAutoBindModule.java, dbmigrate/src/main/java/se/fortnox/reactivewizard/dbmigrate/LiquibaseMigrateProvider.java, dbmigrate/src/test/java/se/fortnox/reactivewizard/dbmigrate/LiquibaseAutoBindModuleTest.java, dbmigrate/test.bind.yml
The provider strategy did not work since providers are not automatically bound just by implementing Provider interface.
And since the migrations are run in the preBind step of the AutoBindModule I am reverting to good old class injection.
Also added a test that will fail if we break this functionality again.
=> fix liquibase migrations

client/src/main/java/se/fortnox/reactivewizard/client/HttpClient.java, client/src/test/java/se/fortnox/reactivewizard/client/HttpClientTest.java
All request in HttpClient are sent with a host header. When a header param "Host" is specified, it is used,
otherwise the host from the http client config is used
=> Add host in headers in http client requests

client/src/main/java/se/fortnox/reactivewizard/client/HttpClient.java, client/src/test/java/se/fortnox/reactivewizard/client/HttpClientTest.java, jaxrs-api/src/main/java/se/fortnox/reactivewizard/jaxrs/FieldError.java, jaxrs-api/src/test/java/se/fortnox/reactivewizard/jaxrs/FieldErrorTest.java
In case of a rw service calling another rw service that generates an error, the fielderrors from that error is lost when handling the error in HttpClient. 
This tries to make sure that the fielderrors are set on the DetailedError cause.
=> Parse field errors from WebExceptions when handling errors in HttpClient

test/src/main/java/se/fortnox/reactivewizard/test/TestUtil.java, test/src/test/java/se/fortnox/reactivewizard/test/TestUtilTest.java
It causes Mockito to throw errors when you have multiple calls in a timeout() verification.
=> Do not throw error in mockito matcher's describeTo method

client/src/main/java/se/fortnox/reactivewizard/client/BasicAuthConfig.java, client/src/main/java/se/fortnox/reactivewizard/client/HttpClient.java, client/src/main/java/se/fortnox/reactivewizard/client/HttpClientConfig.java, client/src/test/java/se/fortnox/reactivewizard/client/HttpClientTest.java
I've been sending auth headers with @HeaderParam on each endpoint for a while and realized it would make sense to actually add this to the framework :) 
It simply works by adding basicAuth to your config:
```
httpClient:
url: myhost.com
basicAuth:
username: root
password: hunter2
```
This will add an Authorization-header with Basic <base64-encoded auth>
=> Add support for sending basic auth to consumed services

test/pom.xml
blitz4j has a version of jackson-core that conflicts with other version that we ourselfes define so this excludes this dependency from blitz4j
=> exclude jackson-core dependency

dao/src/main/java/se/fortnox/reactivewizard/db/ObservableStatementFactory.java, dao/src/test/java/se/fortnox/reactivewizard/db/LoggingTest.java, dao/src/test/java/se/fortnox/reactivewizard/db/MockDb.java
Before this change of order, a caller of DAO that uses backpressure would affect the measured time of the db statement.
=> Do not measure time including backpressure for DAO calls

jaxrs/src/main/java/se/fortnox/reactivewizard/jaxrs/JaxRsRequestHandler.java, jaxrs/src/test/java/se/fortnox/reactivewizard/jaxrs/JaxRsResourceTest.java, jaxrs/src/test/java/se/fortnox/reactivewizard/utils/JaxRsTestUtil.java
There is information about the full path when making a request.
But when answering a request the full path is not to be found.
This pr solves that so that you can get the path of the resource that will answer the request
=> expose path

client/src/main/java/se/fortnox/reactivewizard/client/HttpClient.java, client/src/test/java/se/fortnox/reactivewizard/client/HttpClientTest.java
Since the JaxRsMeta is always the same for a particular method it seems wise to cache this and avoid a lot of processing and annotation parsing in each and every outgoing request.
=> cache metadata for outgoing requests

utils/pom.xml, utils/src/main/java/se/fortnox/reactivewizard/util/ReflectionUtil.java, utils/src/test/java/se/fortnox/reactivewizard/util/ReflectionUtilTest.java
When using method interceptors in Guice a dynamic subclass is
created of the intercepted class. This causes getOverriddenMethod to
not find the correct interface method. This is solved by simply
skipping the generated subclasses when traversing the class tree.
For example, before this, using a class interceptor on the implementation of a jax rs resource will result in the framework not finding parameter annotations such as @QueryParam on method parameters due to the resource interface not being declared on the generated subclass.
=> Make ReflectionUtil.getOverriddenMethod play nice with cglib

server/src/main/java/se/fortnox/reactivewizard/server/RxNettyServer.java, server/src/test/java/se/fortnox/reactivewizard/server/RxNettyServerTest.java
Shutdown Netty server gracefully.
Delay Netty shutdown before resolving shutdown dependency (if there is one).
> Shutting down a Netty application is usually as simple as shutting down all EventLoopGroups you created via shutdownGracefully(). It returns a Future that notifies you when the EventLoopGroup has been terminated completely and all Channels that belong to the group have been closed.
=> Shutdown Netty server gracefully.

dao/src/main/java/se/fortnox/reactivewizard/db/ObservableStatementFactory.java
Kept constructor to avoid breaking change.
=> Do not log statement arguments to avoid sensitive data in logs

dao/src/main/java/se/fortnox/reactivewizard/db/ObservableStatementFactory.java, dao/src/main/java/se/fortnox/reactivewizard/db/transactions/Transaction.java, dao/src/main/java/se/fortnox/reactivewizard/db/transactions/TransactionStatement.java
Before this change, each statement of a transaction was subscribed on the scheduler associated with the DbProxy. This is now changed so that the only execution on the scheduler will be the last statement in the transaction (the actual execution of the transaction).
=> Change transactional statements to avoid subscription on other thread

dao/src/main/java/se/fortnox/reactivewizard/db/transactions/DaoTransactionsImpl.java, dao/src/test/java/se/fortnox/reactivewizard/db/DaoTransactionsTest.java
A call to .last (expecting at least 1 element in the stream) prevented that.
Switching to .ignoreElements().cast(Void.class)
=> making the database accept a set of void DaoObservables.

jaxrs/src/main/java/se/fortnox/reactivewizard/jaxrs/JaxRsResourceInterceptors.java
Since JaxRsRequestHandler is public and this class is an argument in the constructors this class must be public too
=> Making class public

bootstrap/src/main/java/se/fortnox/reactivewizard/Main.java
Effectively replace e.printStackTrace() with a logger call.
=> Use log4j to log startup errors

dao/src/main/java/se/fortnox/reactivewizard/db/ObservableStatementFactory.java, dao/src/test/java/se/fortnox/reactivewizard/db/ObservableStatementFactoryTest.java
When using Scheduler.io(), creating a worker for each transaction in
ObservableStatementFactory without releasing them never lets the
scheduler reuse workers and will create threads until there are no
more resources left.
=> Release newly created scheduler workers after use

config/src/main/java/se/fortnox/reactivewizard/config/ConfigReader.java, config/src/test/java/se/fortnox/reactivewizard/config/ConfigReaderTest.java, config/src/test/java/se/fortnox/reactivewizard/config/TestConfigNewLine.java, config/src/test/resources/testconfig-newline.yml
Newlines are read as strings if a multidimensional list is added to configmap.
Example of YAML structure that dont work in configmap:
`nicheBanks:  clients:    - testclient      - "12345"`
Error message:
`ERRO[2020-07-08T10:19:01.954502254+02:00] v1.ConfigMap.Data: ReadString: expects " or n, but found [, error found in #10 byte of ...|clients":[{"testclient|..., bigger context ...|3.8","database.port":"1234","nichebanks.clients":[ {"testclient":["12345"]}]},"kind":"Co|...`
=> Cannot read multidimensional lists in configmap

client/pom.xml, client/src/main/java/se/fortnox/reactivewizard/client/HttpClient.java, client/src/main/java/se/fortnox/reactivewizard/client/ObservableWithResponse.java, client/src/main/java/se/fortnox/reactivewizard/client/Response.java, client/src/main/java/se/fortnox/reactivewizard/client/SingleWithResponse.java, client/src/test/java/se/fortnox/reactivewizard/client/HttpClientTest.java, client/src/test/java/se/fortnox/reactivewizard/client/HttpClientTestUtil.java
Sending the api call through this new fullResponse method will return a wrapped object containing data, status and headers from the response.
Lets say you have a UserResource like this:
```java
interface UserResource {
Observable<User> getUsers();
}
```
The normal way to use it is 
```java
userResource.getUsers().map(listofusers -> {
//inspect data
return listofusers
});
```
With this method you can
```java
HttpClient.fullResponse(userResource.getUsers()).map(responsewithdata -> {
//inspect headers
responsewithdata.getHeaders()
//inspect status
responsewithstatus.getStatus()
//inspect data
responsewithstatus.getData();
return responsewithdata.getData();
});
```
=> Supporting getting the meta data from the response from an api call..

client/src/main/java/se/fortnox/reactivewizard/client/HttpClient.java, client/src/test/java/se/fortnox/reactivewizard/client/HttpClientTest.java, jaxrs/src/main/java/se/fortnox/reactivewizard/ExceptionHandler.java, jaxrs/src/main/java/se/fortnox/reactivewizard/jaxrs/RequestLogger.java, jaxrs/src/test/java/se/fortnox/reactivewizard/jaxrs/ExceptionHandlerTest.java, jaxrs/src/test/java/se/fortnox/reactivewizard/jaxrs/RequestLoggerTest.java
The purpose of this change is to allow us to hide the value of specific headers that contains sensitive information.
Right now, only the Authorization header is redacted.
=> Redact value of Authorization header from logs

client/src/main/java/se/fortnox/reactivewizard/client/ObservableWithResponse.java, client/src/main/java/se/fortnox/reactivewizard/client/SingleWithResponse.java, client/src/test/java/se/fortnox/reactivewizard/client/HttpClientTest.java
Our subsystem uses it's own subclass extending HttpClient and makes the original solution not working at all times. We need a way to create new ObservableWithResponses when our internal httpclient applies some some operators on the ObservableWithResponse.
This was a way to make it possible but not too easy so that everyone would use it.
=> Added a way to wrap an Observable-/SingleWithResponse

jaxrs/src/main/java/se/fortnox/reactivewizard/jaxrs/params/deserializing/EnumDeserializer.java, jaxrs/src/test/java/se/fortnox/reactivewizard/jaxrs/params/deserializing/EnumDeserializerTest.java
Allowing for a queryparam asc to be resolved to the enum ASC
Trying the exact casing first, and if that fails checking upper case.
Found enums that was not upper cased so I couldn't always make the check uppercase
=> Making the enum deserializer resolve asc to ASC enum.

client/src/main/java/se/fortnox/reactivewizard/client/HttpClient.java, client/src/test/java/se/fortnox/reactivewizard/client/HttpClientTest.java, client/src/test/java/se/fortnox/reactivewizard/client/HttpClientTestUtil.java
When receiving an empty response we didn't get the meta data either.
This should solve that
=> adding support for responses that are empty in combination with getFullResponse

server/src/main/java/se/fortnox/reactivewizard/server/RwServer.java, server/src/main/java/se/fortnox/reactivewizard/server/ServerConfig.java, server/src/test/java/se/fortnox/reactivewizard/server/RwServerGzipTest.java
Gzip will be enabled if we set enableGzip = true in ServerConfig.
Compression will only be enabled for the following mime-types.
- text/plain
- application/xml
- text/css 
- application/x-javascript
- application/json
We will compress response payloads exceeding 1000 bytes. Chunked responses are not compressed.
Resources with stream annotation will not be compressed ( and should not be ).
=> Added possibility to enable gzip for certain mime-types.

.github/workflows/on_release_publish_to_maven.yml, pom.xml
The gpg-private-key must be passed in directly.
The other params must be env:s 
And we have to prevent the gpg plugin from using pinentry programs
Tried this solution on another repo of mine and it fails (as expected) at the very last step of the deploying to nexus since my artifact is bogus. But runs without previous errors until then
=> Rassmate patch 2

client/src/main/java/se/fortnox/reactivewizard/client/HttpClient.java, client/src/test/java/se/fortnox/reactivewizard/client/HttpClientTest.java, jaxrs/src/main/java/se/fortnox/reactivewizard/ExceptionHandler.java, jaxrs/src/main/java/se/fortnox/reactivewizard/jaxrs/RequestLogger.java, jaxrs/src/test/java/se/fortnox/reactivewizard/jaxrs/RequestLoggerTest.java
This change allows you to mark specified headers as sensitive on resources for outgoing calls, redacting the header values from logging.
Example: `HttpClient.markHeaderAsSensitive(someResource, "cookie")`
=> Mark headers as sensitive on resources for outgoing calls

client/src/main/java/se/fortnox/reactivewizard/client/HttpClient.java, jaxrs/src/test/java/se/fortnox/reactivewizard/jaxrs/RequestLoggerTest.java
Should supply a TreeSet with a Comparator to `getHeaderValuesOrRedact`, in order to properly validate if Set contains header or not - regardless of casing.
Missed this in previous PR: #219
=> Fix failing test-case in RequestLoggerTest

client/src/test/java/se/fortnox/reactivewizard/client/HttpClientTest.java, dao/src/test/java/se/fortnox/reactivewizard/db/deserializing/DeserializerUtilTest.java, server/src/test/java/se/fortnox/reactivewizard/server/RwServerTest.java, test/src/main/java/se/fortnox/reactivewizard/test/LoggingMockUtil.java, test/src/test/java/se/fortnox/reactivewizard/test/LoggingMockUtilTest.java
When we verify our log messages in our testing, we always need to take care of the exceptions thrown by LoggingMockUtil. This change will just wrap the exceptions in a runtime exception, so that we don't need to care about adding error handling.🎃
=> Removed the verbose checked exceptions thrown by LoggingMockUtil

client/src/main/java/se/fortnox/reactivewizard/client/HttpClientConfig.java, client/src/main/java/se/fortnox/reactivewizard/client/ReactorRxClientProvider.java, client/src/test/java/se/fortnox/reactivewizard/client/HttpClientTest.java
A single failure should not cause the health recorder to report unhealthy. Adding a config for this, and also adding a config for how long a connection can remain idle before thrown away.
=> make the httpclient more resilient to failures when connecting.

.travis.yml, pom.xml, server/pom.xml, server/src/main/java/se/fortnox/reactivewizard/server/RwServer.java, server/src/main/java/se/fortnox/reactivewizard/server/ServerConfig.java, server/src/test/java/se/fortnox/reactivewizard/server/RwServerGracefulShutdownTest.java, server/src/test/java/se/fortnox/reactivewizard/server/RwServerTest.java
Removed tests for graceful shutdown since they did not test what was intended.
Removed LoopResources from RwServer since it was never used.
Upped reactor-bom to SR17.
=> Added five second wait before server shutdown for improved Kubernetes interoperability

.travis.yml
Since we no longer use it and there was a security issue with the bash uploader.
=> Remove codecov

jaxrs/src/main/java/se/fortnox/reactivewizard/jaxrs/JaxRsResource.java, jaxrs/src/main/java/se/fortnox/reactivewizard/jaxrs/response/ResponseDecorator.java, jaxrs/src/test/java/se/fortnox/reactivewizard/jaxrs/ResponseDecoratorTest.java
Generalizes `ResponseDecorator` to use a `ResponseDecorations` object rather than just response headers. Uses a builder to construct the decorated `Observable`.
```java
return ResponseDecorator.of(just("body"))
.withHeaders(Map.of("Location", "/somewhere-else"))
.withStatus(HttpResponseStatus.MOVED_PERMANENTLY)
.build();
```
```java
Map<String, String> headers = new HashMap<>();
AtomicReference<HttpResponseStatus> status = new AtomicReference<>(null);
return ResponseDecorator.of(defer(() -> {
headers.put("Location", "/somewhere-else");
status.set(HttpResponseStatus.MOVED_PERMANENTLY);
return just("body");
}))
.withHeaders(headers)
.withStatus(status)    
.build();
```
=> Make it possible to set the response status dynamically

jaxrs-api/src/main/java/se/fortnox/reactivewizard/jaxrs/SuppressMissingPathParam.java, jaxrs/src/main/java/se/fortnox/reactivewizard/jaxrs/CheckForMissingPathParams.java, jaxrs/src/test/java/se/fortnox/reactivewizard/jaxrs/CollidingTestInterfaces.java, jaxrs/src/test/java/se/fortnox/reactivewizard/jaxrs/JaxRsResourceTest.java, jaxrs/src/test/java/se/fortnox/reactivewizard/jaxrs/MissingPathParamTestInteraces.java
There were issues with some client interfaces having path params that was later resolved by RW internal so we need some way to get around those kind of use cases.
=> Added possibility to suppress missing path param errors.

client/src/main/java/se/fortnox/reactivewizard/client/RestClientFactory.java, client/src/test/java/se/fortnox/reactivewizard/client/HttpClientTest.java, config/pom.xml, config/src/main/java/se/fortnox/reactivewizard/config/ConfigReader.java, config/src/test/java/se/fortnox/reactivewizard/config/ConfigReaderTest.java, config/src/test/java/se/fortnox/reactivewizard/config/EmptyConfigRecord.java, config/src/test/java/se/fortnox/reactivewizard/config/TestConfigRecord.java, config/src/test/resources/testconfig-empty.yml, dao/src/test/java/se/fortnox/reactivewizard/db/DbResultSetDeserializerTest.java, dao/src/test/java/se/fortnox/reactivewizard/db/DbTestObjRecord.java, dao/src/test/java/se/fortnox/reactivewizard/db/ParameterizedQueryTest.java, jaxrs/src/main/java/se/fortnox/reactivewizard/jaxrs/params/annotated/BeanParamResolver.java, jaxrs/src/test/java/se/fortnox/reactivewizard/jaxrs/JaxRsResourceTest.java, jaxrs/src/test/java/se/fortnox/reactivewizard/jaxrs/ParamEntity.java, jaxrs/src/test/java/se/fortnox/reactivewizard/jaxrs/ParamEntityRecord.java, json/pom.xml, json/src/main/java/se/fortnox/reactivewizard/json/JsonDeserializerFactory.java, json/src/main/java/se/fortnox/reactivewizard/json/JsonSerializerFactory.java, logging/pom.xml, metrics/pom.xml, pom.xml, utils/pom.xml, validation/src/test/java/se/fortnox/reactivewizard/validation/ConfigValidationTest.java, validation/src/test/java/se/fortnox/reactivewizard/validation/ValidationExamples.java
* Had a breaking change in datetime offset serialization that needed to be configured for previous behavior
* Additional configuration needed in internal framework
=> Improve support for records

dao/src/main/java/se/fortnox/reactivewizard/db/DbProxy.java, dao/src/main/java/se/fortnox/reactivewizard/db/ObservableStatementFactory.java, dao/src/main/java/se/fortnox/reactivewizard/db/statement/AbstractDbStatementFactory.java, dao/src/main/java/se/fortnox/reactivewizard/db/statement/DbStatementFactory.java, dao/src/main/java/se/fortnox/reactivewizard/db/statement/SelectStatementFactory.java, dao/src/main/java/se/fortnox/reactivewizard/db/statement/Statement.java, dao/src/main/java/se/fortnox/reactivewizard/db/statement/UpdateStatementExecutorReturningCountFactory.java, dao/src/main/java/se/fortnox/reactivewizard/db/statement/UpdateStatementReturningGeneratedKeyFactory.java, dao/src/main/java/se/fortnox/reactivewizard/db/transactions/DaoObservable.java, dao/src/main/java/se/fortnox/reactivewizard/db/transactions/DaoTransactions.java, dao/src/main/java/se/fortnox/reactivewizard/db/transactions/DaoTransactionsImpl.java, dao/src/main/java/se/fortnox/reactivewizard/db/transactions/Transaction.java, dao/src/main/java/se/fortnox/reactivewizard/db/transactions/TransactionStatement.java, dao/src/test/java/se/fortnox/reactivewizard/db/DaoObservableTest.java, dao/src/test/java/se/fortnox/reactivewizard/db/DaoTransactionsTest.java, dao/src/test/java/se/fortnox/reactivewizard/db/ObservableStatementFactoryTest.java
Instead of creating multiple observables, now one is created that executes the transaction.
It should be backwards compatible. I deprecated the createTransaction-methods, and when we are sure that no one uses them we can rewrite the transaction-stuff totally and get rid of those cross-references between objects and make a more clean implementation.
Commiting a transaction with 24.000 inserts takes around 20 seconds, 100.000 took more than 15 minutes.
This change gets it down to 3 seconds for 24k and around 20-30 seconds for 100k.
And the problem was that it creates so many observables. RxJava simply had too much to do. It creates the observables sequentially.
=> Rewrite creation of transactions

dao/src/main/java/se/fortnox/reactivewizard/db/transactions/DaoTransactionsImpl.java, dao/src/test/java/se/fortnox/reactivewizard/db/DaoTransactionsTest.java
The @Inject annotated constructor must be present for dependency injection to work for this interface.
=> restore @Inject annotated empty constructor

dao/src/main/java/se/fortnox/reactivewizard/db/DbProxy.java, utils/src/main/java/se/fortnox/reactivewizard/util/ReflectionUtil.java, utils/src/test/java/se/fortnox/reactivewizard/util/ReflectionUtilTest.java
When you recompile a class during a debug session, it will be hot reloaded and replace the existing class. However, dao instances that has already been injected will still be using the old version of the interface and queries will therefore not update. This PR fixes that bug and allows for hot reloading to work again.
=> Fix support for hot reload of dao-method annotations

dao/src/main/java/se/fortnox/reactivewizard/db/transactions/ConnectionScheduler.java, dao/src/main/java/se/fortnox/reactivewizard/db/transactions/DaoTransactionsImpl.java, dao/src/test/java/se/fortnox/reactivewizard/db/DaoTransactionsTest.java
having a ConnectionScheduler with a connectionProvider set.
A daoobservable could have connectionProvider null when created from a DbProxy without a connectionProvier set.
=> Using first available ConnectionScheduler where connectionProvider is set.

dao/src/main/java/se/fortnox/reactivewizard/db/DbProxy.java, dao/src/main/java/se/fortnox/reactivewizard/db/ObservableStatementFactory.java, dao/src/test/java/se/fortnox/reactivewizard/db/DbProxyTest.java, dao/src/test/java/se/fortnox/reactivewizard/db/ObservableStatementFactoryTest.java
This is needed for cases when the scheduler needs to be customized per connection. Also makes sense now that ConnectionScheduler exists.
=> DbProxy with both new Scheduler and ConnectionProvider

client/src/test/java/se/fortnox/reactivewizard/client/HttpClientTest.java
The important thing is that we do not retry. Sometimes we dont get a response call count at all but that is also fine.
=> Assert no more than 1 call

test/pom.xml
So that we can use the reactor test module wherever we use this testmodule
=> removed test scope from reactor-test

json/pom.xml, json/src/main/java/com/fasterxml/jackson/databind/ser/LambdaWriter.java, json/src/main/java/se/fortnox/reactivewizard/json/JsonSerializerFactory.java, utils/src/main/java/se/fortnox/reactivewizard/util/LambdaCompiler.java, utils/src/main/java/se/fortnox/reactivewizard/util/MethodGetter.java, utils/src/main/java/se/fortnox/reactivewizard/util/MethodSetter.java, utils/src/main/java/se/fortnox/reactivewizard/util/ReflectionUtil.java, utils/src/test/java/se/fortnox/reactivewizard/util/MethodGetterTest.java, utils/src/test/java/se/fortnox/reactivewizard/util/MethodSetterTest.java, utils/src/test/java/se/fortnox/reactivewizard/util/ReflectionUtilTest.java
By starting the system with -DuseLambdas=false all reflection will use standard reflection calls instead of compiling lambdas.
=> Add possibility to turn off lambda generation

bootstrap/src/main/java/se/fortnox/reactivewizard/Main.java
Use static logger in the Main class instead of fetching on demand.
Fetching the logger on demand at exception caused no output to be shown from the exception
=> Use static logger in main

utils/src/main/java/se/fortnox/reactivewizard/util/FluxRxConverter.java, utils/src/test/java/se/fortnox/reactivewizard/util/FluxRxConverterTest.java
This follows the expectations of using a Mono vs. using a Single.
A Mono emits 0 to 1 value or error while a Single emits 1 value or
error.
Also adds observableToMono(Observable) static converter. Useful when
interacting with third-party apis.
=> Convert Observable to Mono without restricting it to .single()

binding/pom.xml, bootstrap/pom.xml, client/pom.xml, config/pom.xml, dao/pom.xml, dbmigrate/pom.xml, jaxrs/pom.xml, json/pom.xml, metrics/pom.xml, pom.xml, server/pom.xml, test/pom.xml, utils/pom.xml, validation/pom.xml
Moved all(?) dependencies into dependency management and all plugins into plugin management in order not to have to specify versions redundantly and to simplify dependency management downstream.
=> Move dependencies into bom

dbmigrate/src/main/resources/META-INF/services/liquibase.lockservice.LockService
Before 4.0, Liquibase had a custom ServiceLocator class to find classes that implemented Liquibase interfaces. Starting with major version 4, Liquibase switched to the standard java.util.ServiceLoader system to find extension classes.
When we updated to major version 4 of Liquibase our own TimeoutLockService was not loaded anymore. This fix will make sure that Liquibase loads our TimeoutLockService class that solves the shortcomings of Liquibase's own LockService.
https://docs.liquibase.com/tools-integrations/extensions/extension-upgrade-guides/lb-4.0-upgrade-guide.html?Highlight=extension
=> Force releases any locks by Liquibase 4 to avoid crash loops due to unclean shutdowns.

dao/src/main/java/se/fortnox/reactivewizard/db/statement/SelectStatementFactory.java, dao/src/test/java/se/fortnox/reactivewizard/db/DbProxyTest.java, dao/src/test/java/se/fortnox/reactivewizard/db/DbProxyTestDao.java
The reactive streams specification disallows null values in a sequence. Now when the dao module has been migrated to project reactor we cannot return null values in a reactive stream. We do that when we select specific columns from a database, that may be null.  Consider the following:
```
@Select( "select may_be_null_column from table where id = :id" )
Flux<String> getStuff(Integer id);
```
Here may_be_null_column may be null.
Backward compatibility is hard to get here.  we can either: 
* Ignore the null values returned in the sequence
* Throw an exception stating that returning null values cannot be done. 
We went with the "throw an exception" since ignoring values might be more dangerous because it will hide the problem. As well the user can get around the issue by wrapping the …
=> Added an error message when trying to return null values from the database as part of the reactive stream.

jaxrs/src/main/java/se/fortnox/reactivewizard/jaxrs/JaxRsRequest.java, jaxrs/src/test/java/se/fortnox/reactivewizard/jaxrs/JaxRsResourceTest.java
Changed log level from error to info for failure to decode http query params.
=> Changed log level for decode failure

dao/src/main/java/se/fortnox/reactivewizard/db/transactions/DaoTransactionsFlux.java, dao/src/main/java/se/fortnox/reactivewizard/db/transactions/DaoTransactionsFluxImpl.java, dao/src/test/java/se/fortnox/reactivewizard/db/DaoTransactionsTest.java, utils/src/main/java/se/fortnox/reactivewizard/util/ReactiveDecorator.java
Since commands sent to a database is typically inserts or updates which normally would return a single integer (number of rows affected) or empty if specified as Mono<Void>
=> execute transaction will now accept Mono and Flux.

utils/src/main/java/se/fortnox/reactivewizard/util/FluxRxConverter.java, utils/src/test/java/se/fortnox/reactivewizard/util/FluxRxConverterTest.java
Added nullchecks to FluxRxConverter.observableToFlux and observableToMono in order to avoid a more obscure error when forgetting to mock a method returning an Observable.
=> Added nullchecks to FluxRxConverter

dbmigrate/src/test/java/se/fortnox/reactivewizard/dbmigrate/LiquibaseAutoBindModuleTest.java, json/pom.xml, json/src/main/java/se/fortnox/reactivewizard/json/JsonConfig.java, json/src/main/java/se/fortnox/reactivewizard/json/JsonSerializerFactory.java, json/src/test/java/se/fortnox/reactivewizard/json/JsonSerializerFactoryTest.java
* which is "true" by default, but is not compatible with "@JsonUnwrapped" annotation usage at the same time;
* so if one would like to use the aforementioned annotation one could switch serializer modifier configuration off.
=> Introduce "json.useLambdaSerializerModifier" configuration

jaxrs/src/main/java/se/fortnox/reactivewizard/jaxrs/params/deserializing/CustomClassDeserializerFactory.java, jaxrs/src/main/java/se/fortnox/reactivewizard/jaxrs/params/deserializing/DeserializerFactory.java, jaxrs/src/test/java/se/fortnox/reactivewizard/jaxrs/JaxRsResourceTest.java, utils/src/main/java/se/fortnox/reactivewizard/util/LambdaCompiler.java
Follows the JAX-RS spec by allowing classes with:
* A static `valueOf(String)`-method
* A static `fromString(String)`-method
* A `String`-constructor
=> Make it easier to use custom classes as request parameters

client/src/test/java/se/fortnox/reactivewizard/client/FluxClientTest.java, pom.xml, test/pom.xml
Added MockitoExtension dependency in test module to be able to use `@Mock` annotation in JUnit5 tests.
Added example of usage in FluxClientTest.
Removed superfluous dependency management for reactive-streams.
Updated description in root pom.
=> Added MockitoExtension dependency

jaxrs/src/main/java/se/fortnox/reactivewizard/ExceptionHandler.java, jaxrs/src/test/java/se/fortnox/reactivewizard/ExceptionHandlerTest.java, test/src/main/java/se/fortnox/reactivewizard/test/LoggingVerifier.java, test/src/test/java/se/fortnox/reactivewizard/test/LoggingVerifierTest.java
Handle CancellationException in the same way as ClosedChannelException and AbortedException, since it can occur when the inbound connection is closed.
=> Log CancellationException as debug

client/src/main/java/se/fortnox/reactivewizard/client/HttpClient.java, client/src/main/java/se/fortnox/reactivewizard/client/RequestBuilder.java, client/src/test/java/se/fortnox/reactivewizard/client/HttpClientStreamingTest.java, client/src/test/java/se/fortnox/reactivewizard/client/HttpClientTest.java
RequestBuilder now holds content in a Publisher<? extends byte[]> instead of byte[]. This allows for methods in jaxrs interfaces to take Publisher<? extends byte[]> as a body argument, resulting in a streamed upload since Netty is ok with that.
HttpClientStreamingTest verifies that a streamed upload is using a chunked transfer and that an upload can be streamed from a file that is being downloaded.
Perhaps verifying that the size downloaded equals the size uploaded doesn't help much. I used the test to verify that memory usage didn't increase with large files (gigabytes).
=> Add support for streaming upload using HttpClient

dbmigrate/src/test/java/se/fortnox/reactivewizard/dbmigrate/LiquibaseMigrateProviderTest.java, server/src/test/java/se/fortnox/reactivewizard/server/CompositeRequestHandlerTest.java, test/src/main/java/org/mockito/configuration/MockitoConfiguration.java
Make smart-nulls the default answer in Mockito in order to find test errors easier.
See https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/Mockito.html#RETURNS_SMART_NULLS
=> Make smart-nulls the default Mockito answer

config/src/test/java/se/fortnox/reactivewizard/config/MockConfigFactory.java, config/src/test/java/se/fortnox/reactivewizard/config/MockConfigFactoryTest.java
MockConfigFactory now creates a lenient mock in order to work with TestInjector under strict settings.
=> Make MockConfigFactory work with strict mock settings

jaxrs/src/main/java/se/fortnox/reactivewizard/jaxrs/params/deserializing/BigDecimalDeserializer.java, jaxrs/src/main/java/se/fortnox/reactivewizard/jaxrs/params/deserializing/DeserializerFactory.java, jaxrs/src/main/java/se/fortnox/reactivewizard/jaxrs/params/deserializing/LocalDateTimeDeserializer.java, jaxrs/src/test/java/se/fortnox/reactivewizard/jaxrs/JaxRsResourceTest.java, jaxrs/src/test/java/se/fortnox/reactivewizard/jaxrs/params/deserializing/BigDecimalDeserializerTest.java, jaxrs/src/test/java/se/fortnox/reactivewizard/jaxrs/params/deserializing/DeserializerFactoryTest.java, jaxrs/src/test/java/se/fortnox/reactivewizard/jaxrs/params/deserializing/LocalDateTimeDeserializerTest.java, server/src/main/java/se/fortnox/reactivewizard/server/ServerModule.java
This provides the possibility for framework users to extend the functionality by registering custom parameter Deserializers. This is done the same way as for RequestParameterSerializers, letting implementers use Guice Multibinder to add more.
=> Add support to provide custom parameter Deserializers

validation/src/main/java/se/fortnox/reactivewizard/validation/ValidatorUtil.java, validation/src/test/java/se/fortnox/reactivewizard/validation/InputValidationTest.java, validation/src/test/java/se/fortnox/reactivewizard/validation/ValidationExamples.java
Our team noticed an inconsistency between validating single objects and iterables passed as parameters in the API. Consider the following:
_// someObject is validated by default if it has validation annotations_
someResource.create(**SomeObject** object);
_// The same someObject contained in a list is NOT validated by default_
someResource.create(List<**SomeObject**> objects);
_// For iterables, you have to explicitly ask for validation of the list using the @Valid annotation, which will cascade to the objects contained in the iterable_
someResource.create(@Valid List<**SomeObject**> objects);
The risk with this inconsistency is that developers assumes that iterables are validated the same as single objects. This PR contains a suggestion for an implementation that introduces validation of …
=> Objects contained in iterables are now validated

dao/pom.xml, dao/src/main/java/se/fortnox/reactivewizard/db/ReactiveStatementFactory.java, dao/src/main/java/se/fortnox/reactivewizard/db/statement/AbstractDbStatementFactory.java, dao/src/main/java/se/fortnox/reactivewizard/db/statement/SelectStatementFactory.java, dao/src/main/java/se/fortnox/reactivewizard/db/statement/UpdateStatementReturningGeneratedKeyFactory.java, dao/src/test/java/se/fortnox/reactivewizard/db/DaoTest.java, dao/src/test/java/se/fortnox/reactivewizard/db/DaoTransactionsTest.java
Changed DAO behavior when MonoSink is involved such that a call is made to either MonoSink::success(T) or MonoSink::success() but never both.
Despite the fact that a MonoSink::success() should be able to be called multiple times, this resolves an ambiguous backpressure behavior when a DAO method is returned in a concatMap.
=> Changed DAO behavior when MonoSink is involved.

binding/pom.xml, bootstrap/pom.xml, client/src/main/java/se/fortnox/reactivewizard/client/HttpClient.java, client/src/test/java/se/fortnox/reactivewizard/client/HttpClientTest.java, coverage/pom.xml, dbmigrate/pom.xml, jaxrs-api/src/main/java/se/fortnox/reactivewizard/jaxrs/WebException.java, jaxrs/pom.xml, pom.xml, server/pom.xml
If the body of an error didn't correspond to a DetailedError, but was valid json, some or all of it was discarded.
Now, the error response body will also be in WebException.body, regardless of whether it's valid json.
=> Added body of error response to WebException

test/src/main/java/se/fortnox/reactivewizard/test/LoggingMockUtil.java, test/src/test/java/se/fortnox/reactivewizard/test/LoggingMockUtilTest.java, test/src/test/java/se/fortnox/reactivewizard/test/LoggingVerifierExtensionTest.java, test/src/test/java/se/fortnox/reactivewizard/test/LoggingVerifierTest.java
LoggingMockUtil no longer removes existing appenders when adding a mocked appender. This could sometimes result in console log being lost in tests.
=> Fixed issue where console log was sometimes disabled in tests

client/src/main/java/se/fortnox/reactivewizard/client/HttpClient.java
Changed StreamReadConstraints' maxStringLength from the value given in HttpClientConfig::getMaxResponse to a constant 20 million. This value is what the default value was in Jackson 2.14. Change to HttpClientConfig::maxResponseSize was made when Jackson was upgraded to 2.15. This can cause issues for applications that have multiple instances of HttpClient with different HttpClientConfigs. It is an issue because every HttpClient instantiation is changing the maxStringLength constraint on the same ObjectMapper(and JsonFactory) instance.
An alternative solution here would be to make copies of the ObjectMapper(and JsonFactory) for HttpClients with different HttpClientConfig.
=> Changed StreamReadConstraints' maxStringLength

client/src/main/java/se/fortnox/reactivewizard/client/HttpClientProvider.java
When creating new httpclients in parallell, sometimes a ConcurrentModificationException would be thrown.
=> Use ConcurrentHashMap in HttpClientProvider

jaxrs/src/main/java/se/fortnox/reactivewizard/jaxrs/JaxRsMeta.java, jaxrs/src/test/java/se/fortnox/reactivewizard/jaxrs/JaxRsMetaTest.java
Prevent double leading slash in path when resource interface has no path on itself.
=> Prevent double leading slash in resource path

client/src/main/java/se/fortnox/reactivewizard/client/HttpClient.java, client/src/test/java/se/fortnox/reactivewizard/client/HttpClientTest.java
When passing a null value to a parameter annotated with PathParam in proxied resource method a NullPointerException is thrown with an obscure message.
In this commit, we add a null check and handle the null by throwing an IllegalArgumentException with a message that is more friendly and improves the traceability.
=> Added a nullcheck in the HttpClient for parameters annotated with a PathParam

client/src/main/java/se/fortnox/reactivewizard/client/HttpClient.java, client/src/test/java/se/fortnox/reactivewizard/client/HttpClientTest.java
Disregard charset in Content-Type when parsing response, to avoid unnecessary logging if it differs from the default application/json or the Produces annotation on the resource method.
=> Disregard charset in Content-Type when parsing response

.github/dependabot.yml, pom.xml
Revert com.fasterxml.jackson:jackson-bom from 2.16.0 to 2.15.3 because of issue with custom deserializers.
=> Revert com.fasterxml.jackson:jackson-bom from 2.16.0 to 2.15.3

jaxrs-api/src/main/java/se/fortnox/reactivewizard/jaxrs/WebException.java, jaxrs-api/src/test/java/se/fortnox/reactivewizard/jaxrs/WebExceptionTest.java
Add helper methods for checking if any throwable is a WebException with a particular status or error code.
Keeps a lot of instanceof checks from the production code, helps make it more readable and reduces risk of mistakes.
=> Helper methods for writing WebException conditions

jaxrs-api/src/main/java/se/fortnox/reactivewizard/jaxrs/WebException.java, jaxrs-api/src/test/java/se/fortnox/reactivewizard/jaxrs/WebExceptionTest.java
Correctly set log level to debug when response status is 404 and ignore any other irrelevant differences in the exceptions.
The old code compared exact instances, but using equals we get the expected behaviour. New test that verifies the behaviour has been added as well.
=> Fix setting loglevel to debug when a request fails due to 404

client/pom.xml, dao/pom.xml, jaxrs/pom.xml, server/pom.xml, test/pom.xml
Switch to provided scope for log4j in the test module, in order not to needlessly propagate dependencies on a logging implementation.
=> Switch to provided scope for log4j in the test module

dao/src/main/java/se/fortnox/reactivewizard/db/query/parts/CollectionOptionsQueryPart.java, dao/src/test/java/se/fortnox/reactivewizard/db/CollectionOptionsTest.java
It is questionable whether CollectionOptions should even be usable when the return type of a DAO method is Mono. That said, the limit=limit+1 line should only be applied for DAO methods returning Flux.
=> Fixing query limit=1 failing when the return type of the DAO method is Mono.

jaxrs/src/main/java/se/fortnox/reactivewizard/ExceptionHandler.java, jaxrs/src/test/java/se/fortnox/reactivewizard/ExceptionHandlerTest.java
`io.netty.channel.unix.Errors.NativeIoException` thrown on a `Broken pipe` error should not be interpreted as an internal server error. It should be treated as one of the conditions that terminate the inbound connection. We cannot refer the `NativeIoException` directly here because it's for internal use only. Instead, we are checking for the parent `IOException` class in a combination with the message text.
=> "Broken pipe" error handling

dao/src/main/java/se/fortnox/reactivewizard/db/statement/AbstractDbStatementFactory.java, dao/src/test/java/se/fortnox/reactivewizard/db/DaoTransactionsTest.java
If statement is executed in a transaction then `monoSink` and `fluxSink` are not set for a statement.
If statement is also batched with another statement, then `batch()` and `batchExecuted()` methods are called instead of `execute()` method.
Current `batchExecuted()` method does nothing as `fluxSink` and `monoSink` are always `null`, so `ensureMinimumReached()` method is never called.
=> Check minimum rows affected when executing statement in a batch

jaxrs/src/main/java/se/fortnox/reactivewizard/jaxrs/JaxRsResource.java
This update will try to resolve the real JaxRs resource class names and log those names instead of the proxies at the startup and initialization time.
=> PLAT-3447: Log real JaxRs resource class names

.github/workflows/build.yml, client/src/main/java/se/fortnox/reactivewizard/client/HttpClient.java, client/src/test/java/se/fortnox/reactivewizard/client/HttpClientTest.java, jaxrs/src/main/java/se/fortnox/reactivewizard/jaxrs/JaxRsMeta.java, jaxrs/src/main/java/se/fortnox/reactivewizard/jaxrs/JaxRsResource.java, jaxrs/src/test/java/se/fortnox/reactivewizard/jaxrs/JaxRsMetaTest.java
Add deprecated:true to OUT-metrics when the method has been annotated with @Deprecated.
Also exposes deprecations in JaxRsResource for future use internally, will be used in a PR later on.
This will be used to more easily keep track and report on what deprecated endpoints that the service calls out too (this PR) and what deprecated endpoints of the service is being used (next PR). This is quite hard to keep track of today, so we are planning on implementing a Grafana dashboard as a first step that teams can use.
=> Add deprecated:true to OUT-metrics

.codecov.yml, .editorconfig, .github/dependabot.yml, .github/workflows/build.yml, .github/workflows/deploy_manually.yml, .github/workflows/deploy_on_release.yml, .github/workflows/deploy_tag.yml
Enabled Maven caches
https://github.com/actions/setup-java?tab=readme-ov-file#caching-maven-dependencies
This should save a bunch of time from the builds and, if working properly, not introducing a higher risk of issues :)
Updated YAML formatting in editorconfig and cleaned up the format of the .github/ files
Added myself to dependabot and removed flowertwig 
Updated deploy_on_release.yml to make it work with drafts as well, since `created` only triggers when releases are directly created instead of made as drafts and then published
=> Use bundled JDK and enable Maven caching

api/pom.xml, pom.xml
With this dependency developers will be able to annotate their rest endpoints with swagger openapi annotations which could be used to generate openapi specifications from the code
=> Adding dependency to allow for restapi to add open api annotations

dao/src/main/java/se/fortnox/reactivewizard/db/DaoMethodHandler.java, dao/src/main/java/se/fortnox/reactivewizard/db/DbProxy.java, dao/src/main/java/se/fortnox/reactivewizard/db/ReactiveStatementFactory.java, dao/src/test/java/se/fortnox/reactivewizard/db/DaoMethodHandlerTest.java, dao/src/test/java/se/fortnox/reactivewizard/db/DaoTest.java, dao/src/test/java/se/fortnox/reactivewizard/db/DaoTransactionsTest.java, dao/src/test/java/se/fortnox/reactivewizard/db/DbProxyTest.java, dao/src/test/java/se/fortnox/reactivewizard/db/ReactiveStatementFactoryTest.java, dao/src/test/java/se/fortnox/reactivewizard/db/SlowQueryTest.java, metrics/src/main/java/se/fortnox/reactivewizard/metrics/Metrics.java
**1. Remove resultConverter from ReactiveStatementFactory**
`ReactiveStatementFactory` always creates `Mono` if dao method return type is `Mono` and `Flux` if return type is `Flux`. So it looks like there is no need for a converter.
The check that return type is Mono or Flux was moved to `ReactiveStatementFactory`.
**2. Remove paramSerializer from DbProxy**
There are no usages of `paramSerializer` field in `DbProxy`. I have checked internal RW too. So it looks like it is safe to remove it.
**3. Move dao method related code from ReactiveStatementFactory to DaoMethodHandler**
Currently `DbProxy` has two "roles":
- proxies any dao method
- has fields related to query execution (connectionScheduler, databaseConfig)
And `ReactiveStatementFactory` has two "roles":
- builds Mono or Flux for …
=> DAO module clean up and refactoring

.github/workflows/scorecard.yml
Upgrading Github checkout action to resolve the scoreboard supply-chain security warnings.
=> Upgrading Github checkout action

dao/src/main/java/se/fortnox/reactivewizard/db/DbProxy.java
No reason to cause issues for the services that call DbProxy, but marking the constructor as deprecated to indicate that it needs changing.
=> Re-add old constructor to avoid breaking changes for downstream

config/pom.xml, config/src/test/java/se/fortnox/reactivewizard/config/TestInjector.java, dbmigrate/src/test/java/se/fortnox/reactivewizard/dbmigrate/LiquibaseAutoBindModuleTest.java, logging-api/pom.xml, logging-api/src/main/java/se/fortnox/reactivewizard/logging/LoggingShutdownHandler.java, pom.xml, server/pom.xml, server/src/main/java/se/fortnox/reactivewizard/server/RwServer.java, server/src/test/java/se/fortnox/reactivewizard/server/AbortedRequestHandlingTest.java, server/src/test/java/se/fortnox/reactivewizard/server/NoContentFixConfiguratorTest.java, server/src/test/java/se/fortnox/reactivewizard/server/RwServerGracefulShutdownTest.java, server/src/test/java/se/fortnox/reactivewizard/server/RwServerGzipTest.java, server/src/test/java/se/fortnox/reactivewizard/server/RwServerTest.java
When RW server is shut down, the latest portions of the logs entries are not flushed to the storage, and are often lost. This update enables a new handler that will be called at the end of the shutdown procedure in order to flush the logs.
=> PLAT-3553: Flushing the logs at the server shutdown

pom.xml, test/src/main/java/se/fortnox/reactivewizard/test/RwBlockHoundIntegration.java
Allowing blocking calls inside Jackson's DeserializerCache::_createAndCacheValueDeserializer resolves the IllegalMonitorStateException.
See https://github.com/FasterXML/jackson-databind/pull/4430
This PR resolves the issue we had when upgrading to Jackson 2.17.1. The upgrade to 2.17.1 caused some of our tests to fail with IllegalMonitorStateException. By configuring Blockhound to allow blocking calls inside _createAndCacheValueDeserializer, IllegalMonitorStateException is no longer thrown. You can read more about this issue here https://github.com/FasterXML/jackson-databind/pull/4430#issuecomment-2150633048.
=> Allowing blocking calls inside Jackson's DeserializerCache::_createAndCacheValueDeserializer resolves the IllegalMonitorStateException

dao/src/main/java/se/fortnox/reactivewizard/db/query/ParameterizedQuery.java, dao/src/test/java/se/fortnox/reactivewizard/db/ParameterizedQueryTest.java
Remove check for unnamed parameters as it falsely triggers on JSON operators such as `?|` or `?`, so that queries such as this one can be used:
```
SELECT *
FROM message_projections
WHERE message_json->'categories' ?| array['newsletter', 'spam'];
```
Even after removing the exception thrown, Postgres picks up on the error and throws `org.postgresql.util.PSQLException: No value specified for parameter 1.`
=> Fix support for JSON operators in DAO

bootstrap/src/main/java/se/fortnox/reactivewizard/Main.java, validation/src/main/java/se/fortnox/reactivewizard/validation/ValidationModule.java, validation/src/test/java/se/fortnox/reactivewizard/validation/ValidationModuleTest.java
Validation of the config files seems to be broken for a long time. `ValidatingConfigFactory` did not have effect because its binding was always overridden by the default config factory from the bootstrap binding.
For some reason bootstrap binding was giving the highest priority, thus overriding the bindings of all the auto-bind modules. I could not find any justification for this behaviour. The only class that is bound in the bootstrap module is `ConfigFactory`, and we want it to be overridden by `ValidatingConfigFactory`. It looks like it was a bug.
The modules precedence is fixed so that the bootstrap is at the lowest place, overridden by the rest of the modules.
=> PLAT-3546: Validating Config-files
